version: 2.1
jobs:
  build:
    docker:
      # Use this New Image for Starting things up
      - image: fr3akyphantom/droid-runner:latest # DO Not Change
    environment:
      MANIFEST_BRANCH: "android-10.0"
      VERSION: "3.0.0"
      MAINTAINER: "PBRP Team"
      VENDOR: "xiaomi"
      CODENAME: "joyeuse"
      FLAVOR: "eng"
      TEST_BUILD: "true"
      #EXTRA_CMD: ""
      CHANGELOG: |
         Initial Test Build
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: "ALL IN REMOTE"
          command: |
            # SANITY CHECKS
            if [[ -z $GitHubMail ]]; then echo -e "You haven't configured GitHub E-Mail Address." && exit 1; fi
            if [[ -z $GitHubName ]]; then echo -e "You haven't configured GitHub Username." && exit 1; fi
            if [[ -z $GITHUB_TOKEN ]]; then echo -e "You haven't configured GitHub Token.\nWithout it, recovery can't be published." && exit 1; fi
            if [[ -z $MANIFEST_BRANCH ]]; then echo -e "You haven't configured PitchBlack Recovery Project Manifest Branch." && exit 1; fi
            if [[ -z $VENDOR ]]; then echo -e "You haven't configured Vendor name." && exit 1; fi
            if [[ -z $CODENAME ]]; then echo -e "You haven't configured Device Codename." && exit 1; fi
            if [[ -z $BUILD_LUNCH && -z $FLAVOR ]]; then echo -e "Set at least one variable. BUILD_LUNCH or FLAVOR." && exit 1; fi
            
            [[ ! -d /home/builder/.ccache ]] && mkdir -p /home/builder/.ccache
            cd /home/builder/
            
            id
            whoami
            sudo whoami
            
            docker run --privileged -i --name worker --user builder \
              -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) \
              -e GitHubMail="${GitHubMail}" -e GitHubName="${GitHubName}" -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
              -e CIRCLE_PROJECT_USERNAME="${CIRCLE_PROJECT_USERNAME}" -e CIRCLE_PROJECT_REPONAME="${CIRCLE_PROJECT_REPONAME}" \
              -e CIRCLE_BRANCH="${CIRCLE_BRANCH}" -e CIRCLE_SHA1="${CIRCLE_SHA1}" \
              -e MANIFEST_BRANCH="${MANIFEST_BRANCH}" -e PBRP_BRANCH="${PBRP_BRANCH}" \
              -e USE_SECRET_BOOTABLE="${USE_SECRET_BOOTABLE}" -e SECRET_BR="${SECRET_BR}" \
              -e VERSION="${VERSION}" -e VENDOR="${VENDOR}" -e CODENAME="${CODENAME}" \
              -e BUILD_LUNCH="${BUILD_LUNCH}" -e FLAVOR="${FLAVOR}" \
              -e MAINTAINER="${MAINTAINER}" -e CHANGELOG="${CHANGELOG}" \
              -e TEST_BUILD="${TEST_BUILD}" -e PB_OFFICIAL="${PB_OFFICIAL}" \
              -e PB_ENGLISH="${PB_ENGLISH}" -e EXTRA_CMD="${EXTRA_CMD}" \
              -v "${pwd}:/home/builder:rw,z" \
              -v "/home/builder/.ccache:/srv/ccache:rw,z" \
              --workdir /home/builder/ \
              fr3akyphantom/droid-builder:focal bash \<< EOF
            set -x
            cd /home/builder
            id
            whoami
            sudo whoami
            wget -q https://gist.github.com/rokibhasansagar/b50a2bb71b7876ae6a3d796a53688d0f/raw/remote_build_sec.sh -O build.sh
            set +x
            source build.sh
            EOF
workflows:
  version: 2
  remote_builder:
    jobs:
      - build:
          filters:
            branches:
              only: "a11"
          context: personal-envs
