version: 2.1
jobs:
  build:
    docker:
      # Use this New Image for Starting things up
      - image: fr3akyphantom/droid-runner:latest # DO Not Change
    environment:
      MANIFEST_BRANCH: "android-10.0"
      VERSION: "3.0.0"
      VENDOR: "xiaomi"
      CODENAME: "joyeuse"
      FLAVOR: "eng"
      TEST_BUILD: "true"
      #EXTRA_CMD: ""
      MAINTAINER: "PBRP Team"
      CHANGELOG: |
         Initial Test Build
    working_directory: /home/builder/android
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: "ALL IN REMOTE"
          command: |
            export BUILD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"
            curl -L https://gist.github.com/rokibhasansagar/aeb7a65cfc3a33b2c22a9ec3eebd14a9/raw/remote_builder.sh -o builder.sh
            bash ./builder.sh
workflows:
  version: 2
  remote_builder:
    jobs:
      - build:
          filters:
            branches:
              only: "a11"
          context: personal-envs
