version: 2.1
jobs:
  build:
    docker:
      # Use this New Image for Starting things up
      - image: fr3akyphantom/droid-runner:latest # DO Not Change
    environment:
      MANIFEST_BRANCH: "android-10.0"
      VERSION: "3.0"
      MAINTAINER: "PBRP Team"
      VENDOR: "xiaomi"
      CODENAME: "joyeuse"
      FLAVOR: "eng"
      TEST_BUILD: "true"
      #EXTRA_CMD: ""
      CHANGELOG: |
         Initial Test Build
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: "ALL IN REMOTE"
          command: |
            curl -sL https://gist.github.com/rokibhasansagar/aa74b54c113a38f1ec555201defcb9b3/raw/remote_build.sh -o build.sh
            source build.sh
workflows:
  version: 2
  remote_builder:
    jobs:
      - build:
          filters:
            branches:
              only: "a10"
          context: personal-envs
